server:
  port: 8802

spring:
  profiles:
    active: dev
  application:
    name: cscloud-gateway
  cloud:
    httpclient:
      ok:
        enabled:
          false
    gateway:
      routes:
      - id: cscloud-provider-usc #转发路径的唯一标识
        uri: http://127.0.0.1:8803
        predicates: 
        - Path=/user/**
        filters:
        -  StripPrefix=1
      - id: cscloud-auth-server
        uri: lb://cscloud-auth-server
        predicates:
          - Path=/api/auth/server/**
        filters:
          - StripPrefix=3
      - id: cscloud-auth-admin
        uri: lb://cscloud-auth-admin
        predicates:
          - Path=/api/auth/admin/**
        filters:
          - StripPrefix=3
    httpclientfactories:
    loadbalancer:
      retry:
        enabled: true




  # 门户网站的忽略
  datasource:
    initialization-mode: embedded
gateway:
  ignore:
    url: /jwt/

auth:
  user:
    token-header: Authorization
  client:
    token-header:  Client-Auth
    id: cscloud-gateway  #不填则默认读取spring.application.name
    secret: 8qFGi5lv

feign:
  okhttp:
    enabled: true
