server:
  port: 8802
  
spring:
  profiles:
    active: dev
  application:
    name: cscloud-gateway
  cloud:
    gateway:
      routes:
      - id: cscloud-provider-usc #转发路径的唯一标识
        uri: http://127.0.0.1:8803
        predicates: 
        - Path=/user/**
        filters:
        -  StripPrefix=1
        