spring:
  application:
    name: cscloud-auth-admin
  redis:
    host: 192.168.0.241
    database: 8
    password: huisou
    ssl: false
# 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kefu?useSSL=false&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    tomcat:
      max-active: 20
      max-idle: 8
      initial-size: 10
    druid:
      filter:
        encoding:
          enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: utf-8
      enabled: true
      force-request: true
  zipkin:
    base-url: http://localhost:9411


mybatis:
  mapper-locations:
  - classpath:mapper/**.xml


auth: 
  client: 
    id: cscloud-auth-admin
    token-header: Client-Auth
    client: cscloud-auth-server
    rsa-secret: 123456
    expire: 3600 
    secret: oRU5hIPW
  # 这个是用户访问的权限认证
  user:
    token-header: Authorization
    expire: 14400
    rsa-secret: xx1WET12^%3^(WE45


server:
  port: 8810
  tomcat:
    uri-encoding: UTF-8

# 拦截器配置
feign:
  okhttp:
    enabled: true
  client:
    config:
      cscloud-auth-admin:
        requestInterceptors:
          - com.cscloud.auth.client.interceptor.CustomOkHttpInterceptor
