server:
  port: 8802
  
spring:
  profiles:
    active: dev
  application:
    name: 'cscloud-gateway'
  cloud:
    gateway:
      routes:
        - id: user
          uri: localhost:8803
          predicates:
          - Path=/user/**
            
          
      
      